### ISSUE TITLE
Is there an interest to add cmake based build system ?

### ISSUE THREAD

**Issue by 9prady9** [TopModLab/TopMod#20]
Or any other meta build mechanism to build topmod on all major OSes

**Comment by ShenyaoKe** [comment]
For CMake, not really. I experimented on it once but this is not trivial.
With .pro file, you should be able to build and run the latest TopMod code on macOS and theoretically all OSes. I tested it back in 2017 on a borrowed MacBook (I can double check later). I haven't tried Linux.
To build on macOS, download Qt and launch TopMod/topmod.pro from QtCreator. You should be able to build and run. I roughly remember there are some missing features on macOS though.

Note, topmod is an old project and no one is currently maintaining the code. In 2017, I ported it with latest Qt and C++ compiler with some feature left behind. No code change happens after.

**Comment by 9prady9** [comment]
@ShenyaoKe Thanks for the updates. I have used TopMod when I was at TAMU, was just wondering if it is actively maintained and hence asked if it would perhaps take advantage of cmake. In that case, I will just close the issue.
